### ISSUE TITLE
Getting "No Result returned from addPass

### ISSUE THREAD

**Issue by shiv342** [aguschapuis/react-native-google-wallet#1]
<img width="1440" alt="Screenshot 2024-07-19 at 4 58 47 PM" src="https://github.com/user-attachments/assets/faf81f37-693b-4d57-b76d-f8f8e283ed3a">

I am creating wallet feature using this library but it is not responding .please open this attachment and see what the issue .

**Comment by aguschapuis** [comment]
Hi @shiv342 , this error could be for diferents reasons. Try with this options:

1. Did you check if the issuerEmail , issuerId, passClass are the same created on Pay & Wallet Console ? 
2. Check if you have enabled the Google Wallet API in the console

I think is more possible that the first one solve your problem.
