### ISSUE TITLE
Is a backend required to use Google Wallet API with react-native-google-wallet?

### ISSUE THREAD

**Issue by Delucas06** [aguschapuis/react-native-google-wallet#2]
Hello! I'm using the `react-native-google-wallet` library and would like to know if it's necessary to set up a backend to use the Google Wallet API with this library, or if it's possible to handle the entire integration directly from the app, using only direct calls.

Thank you in advance!

**Comment by PanthersHowl** [comment]
Hi, I am interested in your article

**Comment by aguschapuis** [comment]
Hello @Delucas06 ! Sorry for the delay. On Android, you can create the pass without a backend by simply following the steps in the README.
